### ISSUE TITLE
Double slimscrolls

### ISSUE THREAD

**Issue by Novitoll** [ziscloud/angular-slimscroll#15]
Hello, I'm getting double scroll bars on 1.1.0 version

![image](https://cloud.githubusercontent.com/assets/8348972/8188357/48e7d352-1477-11e5-98e4-3bc3b609c3f1.png)

I'm using the slimscroll directive which works fine and the extra bar is  `<div class="slimScrollBar">`  and it seems it is the default wrapper element. Could you please advise if I need to upgrade to the latest version (1.1.3) or is there any idea? Thanks

**Comment by Novitoll** [comment]
@ziscloud Following up

**Comment by ziscloud** [comment]
@Novitoll I never encounter this issue, could you please share your simple syntax to use this directive.
Second, if you want to upgrade to the latest version, just downland it or change the version number in your bower.json and execute the bower update.

**Comment by Novitoll** [comment]
@ziscloud Thanks, yes it seems I need to upgrade it. Could you please track also the version somewhere at the top of angular-slimscroll.js file, so consumers could define the version easily. Thanks!

**Comment by Novitoll** [comment]
@ziscloud The reason has been found. It comes from the latest jquery.slimscroll.js version (1.3.6), and it works fine with its 1.3.3. Thanks!

**Comment by jmaza** [comment]
I also have this problem. Why doesn't angular-slimscroll use slimscroll.js version (1.3.3) then?

**Comment by silentFred** [comment]
+1

**Comment by silentFred** [comment]
I have the same issue with jquery-smilscroll 1.4.4

**Comment by ziscloud** [comment]
@silentFred, could you please provide a JSFiddle online example to demonstrate your issue?
