### ISSUE TITLE
Slimscroll's height does not adjust on window resizing

### ISSUE THREAD

**Issue by jagmal** [ziscloud/angular-slimscroll#7]
Slimscroll's height does not adjust on window resizing. Is there something that I am missing or is it not supported? If later, can it be fixed?

**Comment by jagmal** [comment]
Thanks for fixing this!

**Comment by immortalcy** [comment]
could you provide a working example on this matter?

**Comment by nicolaib** [comment]
I'm also looking for an example. Can anyone show how to add this attribute to the HTML (I suppose)?
Thanks.
